version: '3.7'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    
    logging:
        driver: "json-file"
        options:
            max-size: "10k"
            max-file: "10"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
      # - ./elastichsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      # - ./ssl:/usr/share/elasticsearch/config/ssl
    ports:
      - 9200:9200  
    networks:
      - elastic

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.8.1
    environment:
      - xpack.apm.enabled=true
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    # volumes:
    #   - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    #   - ./ssl:/usr/share/kibana/config/ssl
    networks:
      - elastic

  # logstash:
  #   container_name: logstash
  #   image: docker.elastic.co/logstash/logstash:8.8.1
  #   volumes:
  #     - ./logstash/:/logstash_dir
  #   command: logstash -f /logstash_dir/logstash.conf
  #   ports:
  #     - 9600:9600
  #   depends_on:
  #     - elasticsearch
  #   networks:
  #     - elastic

  # apm-server:
  #   image: docker.elastic.co/apm/apm-server:8.8.1
  #   container_name: apm-server
  #   environment:
 
  #     - setup.kibana.host=kibana:5601
  #   # volumes:
  #   #   - ./apm-server/apm-server.yml:/usr/share/apm-server/apm-server.yml
  #   ports:
  #     - "8200:8200"
  #   networks:
  #     - elastic
  
  #   depends_on:
  #    - elasticsearch
  #    - kibana

volumes:  
  elasticsearch-data:
    driver: local

networks:
  elastic:
    driver: bridge